import './globals.css'
import { Inter } from 'next/font/google'
import { Header } from './components/common/header'
import { Footer } from './components/common/footer'
import { MainVisual } from './components/common/mv'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
